// generated by revision.bat 
#ifndef FLY_REVISION_H  
#define REVISION 13665 
#ifdef _DEBUG 
  #define REVISION_STR "4 [support::_](debug)" 
  #define L_REVISION_STR L"4 [support::_](debug)" 
#else 
  #define REVISION_STR "4 [support::4c53519]" 
  #define L_REVISION_STR L"4 [support::4c53519]" 
#endif 
#endif 
