:init revision_vars.h

 :Git

  : rev count
  FOR /F %%i IN ('git rev-list HEAD --count') DO set git_rev_count=%%i

  : rev SHA1 short
  FOR /F %%i IN ('git rev-parse --short HEAD') DO set git_rev_sha1=%%i

  : branch name
  FOR /F %%i IN ('git rev-parse --abbrev-ref HEAD') DO set git_branch_name=%%i

  
 : output
 set format_ident=%git_rev_count% [%git_branch_name%::%git_rev_sha1%]
 
 echo // generated by revision.bat > revision.h
 echo #ifndef FLY_REVISION_H >> revision.h 
 echo #define REVISION 13665 >> revision.h
 echo #ifdef _DEBUG >> revision.h
 echo   #define REVISION_STR "%format_ident%(debug)" >> revision.h
 echo   #define L_REVISION_STR L"%format_ident%(debug)" >> revision.h
 echo #else >> revision.h
 echo   #define REVISION_STR "%format_ident%" >> revision.h
 echo   #define L_REVISION_STR L"%format_ident%" >> revision.h
 echo #endif >> revision.h
 echo #endif >> revision.h


