// This code was generated by a tool 
#ifndef FLY_REVISION_H  
#define REVISION 13665 
#ifdef _DEBUG 
  #define REVISION_STR "%bCount% [%bName%_%bSha1%](debug)" 
  #define L_REVISION_STR L"%bCount% [%bName%_%bSha1%](debug)" 
#else 
  #define REVISION_STR "%bCount% [%bName%_%bSha1%]" 
  #define L_REVISION_STR L"%bCount% [%bName%_%bSha1%]" 
#endif 
#endif 
